# Generated by Django 5.2.4 on 2025-07-30 14:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.FloatField()),
                ('precio_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_activada', models.BooleanField(default=False)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha_quantum.accion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarmas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisFundamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PER', models.FloatField(blank=True, null=True)),
                ('ROE', models.FloatField(blank=True, null=True)),
                ('ROI', models.FloatField(blank=True, null=True)),
                ('deuda_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('beneficio_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_intrinseco', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alpha_quantum.accion')),
            ],
        ),
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accion',
            name='cartera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='alpha_quantum.cartera'),
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=50)),
                ('tipo_ingreso', models.CharField(blank=True, choices=[('salario', 'Salario'), ('alquiler', 'Alquileres'), ('dividendos', 'Dividendos'), ('intereses', 'Intereses bancarios o préstamos'), ('ventas', 'Ganancias por venta de activos'), ('autonomo', 'Ingresos como autónomo/profesional'), ('empresa', 'Distribución de beneficios empresariales'), ('subsidios', 'Subsidios o pensiones'), ('regalos', 'Regalos o herencias'), ('otros', 'Otros ingresos')], max_length=50, null=True)),
                ('description', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dividendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha_quantum.accion')),
            ],
        ),
        migrations.CreateModel(
            name='EventoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('tipo_evento', models.CharField(choices=[('resultado', 'Resultado Trimestral'), ('dividendo', 'Dividendo'), ('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha_quantum.accion')),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='alpha_quantum.cartera')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='alpha_quantum.accion')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meses_restantes', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hipoteca_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meses_restantes_hipoteca', models.PositiveIntegerField(default=0)),
                ('gastos_mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10)),
                ('valor_objetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upside', models.FloatField(blank=True, null=True)),
                ('max_52s', models.FloatField(blank=True, null=True)),
                ('min_52s', models.FloatField(blank=True, null=True)),
                ('per', models.FloatField(blank=True, null=True)),
                ('recomendacion', models.CharField(blank=True, choices=[('COMPRAR', 'Comprar'), ('REVISAR', 'Revisar'), ('ESPERAR', 'Esperar')], max_length=20, null=True)),
                ('precio_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
