# Generated by Django 5.2.4 on 2025-08-08 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_quantum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadalquiler',
            name='gastos_mantenimiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='propiedadalquiler',
            name='hipoteca_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='propiedadalquiler',
            name='ingreso_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='propiedadalquiler',
            name='meses_restantes_hipoteca',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propiedadalquiler',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('tipo', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta'), ('DIV', 'Dividendo')], max_length=4)),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('precio', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('comision', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('fecha', models.DateField()),
                ('nota', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
