# Generated by Django 5.2.4 on 2025-07-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_quantum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='precio_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='recomendacion',
            field=models.CharField(blank=True, choices=[('COMPRAR', 'Comprar'), ('REVISAR', 'Revisar'), ('ESPERAR', 'Esperar')], max_length=20, null=True),
        ),
    ]
