# Generated by Django 5.2.4 on 2025-08-08 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_quantum', '0002_alter_propiedadalquiler_gastos_mantenimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('invertido', models.DecimalField(decimal_places=2, max_digits=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_cartera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('user', 'fecha')},
            },
        ),
    ]
