# Generated by Django 5.2.4 on 2025-07-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_quantum', '0002_watchlist_precio_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='consenso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='max_52s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='min_52s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='per',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='upside',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
