# Generated by Django 5.2.4 on 2025-07-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_quantum', '0003_watchlist_consenso_watchlist_max_52s_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='consenso',
            new_name='max_52_sem',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='max_52s',
            new_name='min_52_sem',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='min_52s',
            new_name='precio_objetivo_consenso',
        ),
    ]
