# Generated by Django 5.2.4 on 2025-08-11 08:38

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_quantum', '0003_historicocartera'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividendo',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterUniqueTogether(
            name='dividendo',
            unique_together={('accion', 'fecha')},
        ),
        migrations.AddField(
            model_name='dividendo',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),  # ✅ en lugar de default=1
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dividendo',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dividendo',
            name='ex_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dividendo',
            name='fuente',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='dividendo',
            name='monto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='dividendo',
            name='accion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividendos', to='alpha_quantum.accion'),
        ),
        migrations.RemoveField(
            model_name='dividendo',
            name='cantidad',
        ),
    ]
