# Generated by Django 5.2.4 on 2025-07-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_quantum', '0004_rename_consenso_watchlist_max_52_sem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='precio_objetivo_consenso',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='valor_objetivo',
        ),
    ]
