# Generated by Django 5.2.4 on 2025-08-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_quantum', '0004_alter_dividendo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividendo',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='dividendo',
            name='creado',
        ),
    ]
