# Generated by Django 5.2.4 on 2025-07-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_quantum', '0005_remove_watchlist_precio_objetivo_consenso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='valor_objetivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
