# Generated by Django 5.2.4 on 2025-08-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_quantum', '0005_remove_dividendo_actualizado_remove_dividendo_creado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividendo',
            options={'ordering': ('-fecha',)},
        ),
        migrations.AlterUniqueTogether(
            name='dividendo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dividendo',
            name='nota',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dividendo',
            name='monto',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='dividendo',
            name='ex_date',
        ),
        migrations.RemoveField(
            model_name='dividendo',
            name='fuente',
        ),
    ]
