# Generated by Django 5.2.4 on 2025-07-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_quantum', '0006_watchlist_valor_objetivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='max_52_sem',
            new_name='max_52s',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='min_52_sem',
            new_name='min_52s',
        ),
    ]
