# Generated by Django 5.2.4 on 2025-08-28 09:42

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_quantum', '0006_alter_dividendo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['ticker']},
        ),
        migrations.AddField(
            model_name='cartera',
            name='creada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartera',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartera',
            name='moneda_base',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='sector',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='per',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='precio_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'ticker'], name='alpha_quant_user_id_d68632_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('user', 'ticker'), name='uq_watchlist_user_ticker'),
        ),
    ]
