# Generated by Django 5.2.4 on 2025-07-23 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_quantum', '0007_rename_max_52_sem_watchlist_max_52s_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('tipo_evento', models.CharField(choices=[('resultado', 'Resultados'), ('dividendo', 'Dividendo'), ('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
