# Generated by Django 5.2.4 on 2025-07-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_quantum', '0008_eventofinanciero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventofinanciero',
            name='tipo_evento',
            field=models.CharField(choices=[('resultado', 'Resultado Trimestral'), ('dividendo', 'Dividendo'), ('compra', 'Compra'), ('venta', 'Venta')], max_length=10),
        ),
    ]
