# Generated by Django 5.2.4 on 2025-08-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_quantum', '0011_alter_watchlist_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='watchlist',
            name='uq_watchlist_user_ticker',
        ),
        migrations.RemoveIndex(
            model_name='watchlist',
            name='alpha_quant_user_id_d68632_idx',
        ),
        migrations.RenameIndex(
            model_name='watchlist',
            new_name='alpha_quant_user_id_1445fd_idx',
            old_name='idx_wl_user_lista_ticker',
        ),
        migrations.AlterField(
            model_name='watchlistlista',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
